server.name=CobbleCraft
server.address=127.0.0.1
server.port=25565
pack.version=1.6.1-rc2
launcher.version=1.0.1
discord.url=https://discord.gg/7pBm62xgUr
website.url=https://cobblemon-server-site.pages.dev
